### ISSUE TITLE
Build looking for bundle in wrong directory/path

### ISSUE THREAD

**Issue by WiseKodama** [AppLovin/AppLovin-MAX-Swift-Package#3] opened 2023-12-11 13:51 UTC
Greetings, 

I have added AppLovin SDK via swift package manager, however I am running into the following error when trying to build. 
It seems that it's trying to grab the bundle from the build directory, if I copy and paste the AppLovinSDKResources.bundle into the path where it's searching and modify the name to `AppLovinSDK_AppLovinSDKResources.bundle`, then build will succeed. 

Is this a bug or an oversight of the integration on my end? 

<img width="801" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/25555617/9a353434-e46a-49ff-90b6-47629cf81d83">

**Comment by ritamsarmah** [comment] 2023-12-11 19:41
Hi @WiseKodama,

I just tried out a build with SDK 12.1.0, but unfortunately could not reproduce the error you are seeing. Here are some initial troubleshooting steps I'd try:
- Clean Project: Product > Clean Build Folder
- Reseting the Cache: File > Packages > Reset Package Caches
- Integrating the SDK in a new Xcode project to verify if the problem is specific to your project or not.

If the above steps didn't work, could you share which Xcode/Swift/SDK version you're using for your project? If you're using a `Package.swift` to manage dependencies please share that as well. Thanks!

**Comment by WiseKodama** [comment] 2023-12-12 10:01
Hi @ritamsarmah 

I am using Xcode 14.2, Swift Language Version 5, SDK version 12(Next Major version), targeting iOS 12.0. 

I am not using `Package.swift`, instead it's added directly onto project: 
<img width="768" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/25555617/4a6ed610-82ab-4fa1-b029-daaf33118a2e">

I will try it with a new project, however I still need to somehow solve it for the current one. 
Full disclosure: I am not an iOS dev, I am a game dev, trying to push an update to a 10 year old game.

**Comment by ritamsarmah** [comment] 2023-12-12 22:40
Got it, thanks for that info. There may be some build setting that's causing the issue as you suspect, but it's hard to predict what that could be with the current information we have.

Would you mind sending your project via email to ritam.sarmah@applovin.com so I could inspect the build settings myself?

**Comment by ritamsarmah** [comment] 2024-03-19 23:32
Hi @WiseKodama, if you have any further information, let us know. For now, I'm closing this issue out since we've not received any similar reports, so it's likely related to your project-specific build settings.

**Closed by ritamsarmah** 2024-03-19 23:32 UTC
